import aiohttp
import datetime
from typing import Any
from telebot import types as types, util as util
import logging
import ssl

API_URL: str
logger: logging.Logger
proxy: Any
session: Any
FILE_URL: Any
REQUEST_TIMEOUT: int
MAX_RETRIES: int
REQUEST_LIMIT: int

class SessionManager:
    ssl_context: ssl.SSLContext
    def __init__(self) -> None: ...
    @property
    def session(self) -> aiohttp.ClientSession | None: ...
    @session.setter
    def session(self, value: aiohttp.ClientSession | None) -> None: ...
    async def create_session(self) -> aiohttp.ClientSession: ...
    async def get_session(self) -> aiohttp.ClientSession: ...

session_manager: SessionManager

async def get_me(token: str) -> types.User: ...
async def log_out(token: str) -> bool: ...
async def close(token: str) -> bool: ...
async def get_file(token: str, file_id: str) -> types.File: ...
async def get_file_url(token: str, file_id: str) -> str: ...
async def download_file(token: str, file_path: str) -> bytes: ...
async def set_webhook(token: str, url: str | None = None, certificate: Any | None = None, max_connections: int | None = None, allowed_updates: list[str] | None = None, ip_address: str | None = None, drop_pending_updates: bool | None = None, timeout: int | float | None = None, secret_token: str | None = None) -> bool: ...
async def delete_webhook(token: str, drop_pending_updates: bool | None = None, timeout: int | float | None = None) -> bool: ...
async def get_webhook_info(token: str, timeout: int | float | None = None) -> types.WebhookInfo: ...
async def get_updates(token: str, offset: int | None = None, limit: int | None = None, timeout: int | float | None = None, allowed_updates: list[str] | None = None, request_timeout: int | float | None = None) -> list[types.Update]: ...
async def send_message(token: str, chat_id: int | str, text: str, reply_markup: types.InlineKeyboardMarkup | types.ReplyKeyboardMarkup | types.ReplyKeyboardRemove | types.ForceReply | None = None, parse_mode: str | None = None, disable_notification: bool | None = None, timeout: int | float | None = None, entities: list[types.MessageEntity] | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, reply_parameters: types.ReplyParameters | None = None, link_preview_options: types.LinkPreviewOptions | None = None, business_connection_id: str | None = None, message_effect_id: str | None = None, allow_paid_broadcast: bool | None = None, direct_messages_topic_id: int | None = None, suggested_post_parameters: Any | None = None) -> types.Message: ...
async def get_user_profile_photos(token: str, user_id: int, offset: int | None = None, limit: int | None = None) -> types.UserProfilePhotos: ...
async def get_user_profile_audios(token: str, user_id: int, offset: int | None = None, limit: int | None = None) -> types.UserProfileAudios: ...
async def set_user_emoji_status(token: str, user_id: int, emoji_status_custom_emoji_id: str | None = None, emoji_status_expiration_date: int | None = None) -> bool: ...
async def set_message_reaction(token: str, chat_id: int | str, message_id: int, reaction: list[types.ReactionType] | None = None, is_big: bool | None = None) -> bool: ...
async def get_chat(token: str, chat_id: int | str) -> types.Chat: ...
async def leave_chat(token: str, chat_id: int | str) -> bool: ...
async def get_chat_administrators(token: str, chat_id: int | str) -> list[types.ChatMember]: ...
async def get_chat_member_count(token: str, chat_id: int | str) -> int: ...
async def replace_sticker_in_set(token: str, user_id: int, name: str, old_sticker: str, sticker: types.InputSticker) -> bool: ...
async def set_sticker_set_thumbnail(token: str, name: str, user_id: int, thumbnail: str | None, format: str | None) -> bool: ...
async def set_chat_sticker_set(token: str, chat_id: int | str, sticker_set_name: str) -> bool: ...
async def delete_chat_sticker_set(token: str, chat_id: int | str) -> bool: ...
async def answer_web_app_query(token: str, web_app_query_id: str, result: types.InlineQueryResultBase) -> types.SentWebAppMessage: ...
async def save_prepared_inline_message(token: str, user_id: int, result: types.InlineQueryResultBase, allow_user_chats: bool | None = None, allow_bot_chats: bool | None = None, allow_group_chats: bool | None = None, allow_channel_chats: bool | None = None) -> types.PreparedInlineMessage: ...
async def save_prepared_keyboard_button(token: str, user_id: int, button: types.KeyboardButton) -> Any: ... # botapi 9.6 support when?
async def get_chat_member(token: str, chat_id: int | str, user_id: int) -> types.ChatMember: ...
async def forward_message(token: str, chat_id: str | int, from_chat_id: str | int, message_id: int, disable_notification: bool | None = None, timeout: int | float | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, video_start_timestamp: int | None = None, direct_messages_topic_id: int | None = None, suggested_post_parameters: types.SuggestedPostParameters | None = None, message_effect_id: str | None = None) -> types.Message: ...
async def copy_message(token: str, chat_id: str | int, from_chat_id: str | int, message_id: int, caption: str | None = None, parse_mode: str | None = None, caption_entities: list[types.MessageEntity] | None = None, disable_notification: bool | None = None, reply_markup: types.InlineKeyboardMarkup | types.ReplyKeyboardMarkup | types.ReplyKeyboardRemove | types.ForceReply | None = None, timeout: int | float | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, reply_parameters: types.ReplyParameters | None = None, show_caption_above_media: bool | None = None, allow_paid_broadcast: bool | None = None, video_start_timestamp: int | None = None, direct_messages_topic_id: int | None = None, suggested_post_parameters: types.SuggestedPostParameters | None = None, message_effect_id: str | None = None) -> types.MessageID: ...
async def send_checklist(token: str, business_connection_id: str, chat_id: str | int, checklist: types.Checklist, disable_notification: bool | None = None, protect_content: bool | None = None, message_effect_id: str | None = None, reply_parameters: types.ReplyParameters | None = None, reply_markup: types.InlineKeyboardMarkup | types.ReplyKeyboardMarkup | types.ReplyKeyboardRemove | types.ForceReply | None = None) -> types.Message: ...
async def edit_message_checklist(token: str, business_connection_id: str, chat_id: str | int, message_id: int, checklist: types.Checklist, reply_markup: types.InlineKeyboardMarkup | None = None) -> types.Message | bool: ...
async def send_dice(token: str, chat_id: str | int, emoji: str | None = None, disable_notification: bool | None = None, reply_markup: types.InlineKeyboardMarkup | types.ReplyKeyboardMarkup | types.ReplyKeyboardRemove | types.ForceReply | None = None, timeout: int | float | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, reply_parameters: types.ReplyParameters | None = None, business_connection_id: str | None = None, message_effect_id: str | None = None, allow_paid_broadcast: bool | None = None, direct_messages_topic_id: int | None = None, suggested_post_parameters: types.SuggestedPostParameters | None = None) -> types.Message: ...
async def send_photo(token: str, chat_id: str | int, photo: str | bytes, caption: str | None = None, reply_markup: types.InlineKeyboardMarkup | types.ReplyKeyboardMarkup | types.ReplyKeyboardRemove | types.ForceReply | None = None, parse_mode: str | None = None, disable_notification: bool | None = None, timeout: int | float | None = None, caption_entities: list[types.MessageEntity] | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, has_spoiler: bool | None = None, reply_parameters: types.ReplyParameters | None = None, business_connection_id: str | None = None, message_effect_id: str | None = None, show_caption_above_media: bool | None = None, allow_paid_broadcast: bool | None = None, direct_messages_topic_id: int | None = None, suggested_post_parameters: types.SuggestedPostParameters | None = None) -> types.Message: ...
async def send_paid_media(token: str, chat_id: str | int, star_count: int, media: list[types.InputPaidMedia], caption: str | None = None, parse_mode: str | None = None, caption_entities: list[types.MessageEntity] | None = None, show_caption_above_media: bool | None = None, disable_notification: bool | None = None, protect_content: bool | None = None, reply_parameters: types.ReplyParameters | None = None, reply_markup: types.InlineKeyboardMarkup | types.ReplyKeyboardMarkup | types.ReplyKeyboardRemove | types.ForceReply | None = None, business_connection_id: str | None = None, payload: str | None = None, allow_paid_broadcast: bool | None = None, direct_messages_topic_id: int | None = None, suggested_post_parameters: types.SuggestedPostParameters | None = None) -> types.Message: ...
async def send_media_group(token: str, chat_id: str | int, media: list[types.InputMediaAudio | types.InputMediaDocument | types.InputMediaPhoto | types.InputMediaVideo], disable_notification: bool | None = None, timeout: int | float | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, reply_parameters: types.ReplyParameters | None = None, business_connection_id: str | None = None, message_effect_id: str | None = None, allow_paid_broadcast: bool | None = None, direct_messages_topic_id: int | None = None) -> list[types.Message]: ...
async def send_location(token: str, chat_id: str | int, latitude: float, longitude: float, live_period: int | None = None, reply_markup: types.InlineKeyboardMarkup | types.ReplyKeyboardMarkup | types.ReplyKeyboardRemove | types.ForceReply | None = None, disable_notification: bool | None = None, timeout: int | float | None = None, horizontal_accuracy: float | None = None, heading: int | None = None, proximity_alert_radius: int | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, reply_parameters: types.ReplyParameters | None = None, business_connection_id: str | None = None, message_effect_id: str | None = None, allow_paid_broadcast: bool | None = None, direct_messages_topic_id: int | None = None, suggested_post_parameters: types.SuggestedPostParameters | None = None) -> types.Message: ...
async def edit_message_live_location(token: str, latitude: float, longitude: float, chat_id: str | int | None = None, message_id: int | None = None, inline_message_id: str | None = None, reply_markup: types.InlineKeyboardMarkup | None = None, timeout: int | float | None = None, horizontal_accuracy: float | None = None, heading: int | None = None, proximity_alert_radius: int | None = None, live_period: int | None = None, business_connection_id: str | None = None) -> types.Message | bool: ...
async def stop_message_live_location(token: str, chat_id: str | int | None = None, message_id: int | None = None, inline_message_id: str | None = None, reply_markup: types.InlineKeyboardMarkup | None = None, timeout: int | float | None = None, business_connection_id: str | None = None) -> types.Message | bool: ...
async def send_venue(token: str, chat_id: str | int, latitude: float, longitude: float, title: str, address: str, foursquare_id: str | None = None, foursquare_type: str | None = None, disable_notification: bool | None = None, reply_markup: types.InlineKeyboardMarkup | types.ReplyKeyboardMarkup | types.ReplyKeyboardRemove | types.ForceReply | None = None, timeout: int | float | None = None, google_place_id: str | None = None, google_place_type: str | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, reply_parameters: types.ReplyParameters | None = None, business_connection_id: str | None = None, message_effect_id: str | None = None, allow_paid_broadcast: bool | None = None, direct_messages_topic_id: int | None = None, suggested_post_parameters: types.SuggestedPostParameters | None = None) -> types.Message: ...
async def send_contact(token: str, chat_id: str | int, phone_number: str, first_name: str, last_name: str | None = None, vcard: str | None = None, disable_notification: bool | None = None, reply_markup: types.InlineKeyboardMarkup | types.ReplyKeyboardMarkup | types.ReplyKeyboardRemove | types.ForceReply | None = None, timeout: int | float | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, reply_parameters: types.ReplyParameters | None = None, business_connection_id: str | None = None, message_effect_id: str | None = None, allow_paid_broadcast: bool | None = None, direct_messages_topic_id: int | None = None, suggested_post_parameters: types.SuggestedPostParameters | None = None) -> types.Message: ...
async def send_message_draft(token: str, chat_id: str | int, draft_id: str, text: str, message_thread_id: int | None = None, parse_mode: str | None = None, entities: list[types.MessageEntity] | None = None) -> types.Message: ...
async def send_chat_action(token: str, chat_id: str | int, action: str, timeout: int | float | None = None, message_thread_id: int | None = None, business_connection_id: str | None = None) -> bool: ...
async def send_video(token: str, chat_id: str | int, data: str | bytes, duration: int | None = None, caption: str | None = None, reply_markup: types.InlineKeyboardMarkup | types.ReplyKeyboardMarkup | types.ReplyKeyboardRemove | types.ForceReply | None = None, parse_mode: str | None = None, supports_streaming: bool | None = None, disable_notification: bool | None = None, timeout: int | float | None = None, thumbnail: str | bytes | None = None, width: int | None = None, height: int | None = None, caption_entities: list[types.MessageEntity] | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, has_spoiler: bool | None = None, reply_parameters: types.ReplyParameters | None = None, business_connection_id: str | None = None, message_effect_id: str | None = None, show_caption_above_media: bool | None = None, allow_paid_broadcast: bool | None = None, cover: str | bytes | None = None, start_timestamp: int | None = None, direct_messages_topic_id: int | None = None, suggested_post_parameters: types.SuggestedPostParameters | None = None) -> types.Message: ...
async def send_animation(token: str, chat_id: str | int, data: str | bytes, duration: int | None = None, caption: str | None = None, reply_markup: types.InlineKeyboardMarkup | types.ReplyKeyboardMarkup | types.ReplyKeyboardRemove | types.ForceReply | None = None, parse_mode: str | None = None, disable_notification: bool | None = None, timeout: int | float | None = None, thumbnail: str | bytes | None = None, caption_entities: list[types.MessageEntity] | None = None, width: int | None = None, height: int | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, has_spoiler: bool | None = None, reply_parameters: types.ReplyParameters | None = None, business_connection_id: str | None = None, message_effect_id: str | None = None, show_caption_above_media: bool | None = None, allow_paid_broadcast: bool | None = None, direct_messages_topic_id: int | None = None, suggested_post_parameters: types.SuggestedPostParameters | None = None) -> types.Message: ...
async def send_voice(token: str, chat_id: str | int, voice: str | bytes, caption: str | None = None, duration: int | None = None, reply_markup: types.InlineKeyboardMarkup | types.ReplyKeyboardMarkup | types.ReplyKeyboardRemove | types.ForceReply | None = None, parse_mode: str | None = None, disable_notification: bool | None = None, timeout: int | float | None = None, caption_entities: list[types.MessageEntity] | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, reply_parameters: types.ReplyParameters | None = None, business_connection_id: str | None = None, message_effect_id: str | None = None, allow_paid_broadcast: bool | None = None, direct_messages_topic_id: int | None = None, suggested_post_parameters: types.SuggestedPostParameters | None = None) -> types.Message: ...
async def send_video_note(token: str, chat_id: str | int, data: str | bytes, duration: int | None = None, length: int | None = None, reply_markup: types.InlineKeyboardMarkup | types.ReplyKeyboardMarkup | types.ReplyKeyboardRemove | types.ForceReply | None = None, disable_notification: bool | None = None, timeout: int | float | None = None, thumbnail: str | bytes | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, reply_parameters: types.ReplyParameters | None = None, business_connection_id: str | None = None, message_effect_id: str | None = None, allow_paid_broadcast: bool | None = None, direct_messages_topic_id: int | None = None, suggested_post_parameters: types.SuggestedPostParameters | None = None) -> types.Message: ...
async def send_audio(token: str, chat_id: str | int, audio: str | bytes, caption: str | None = None, duration: int | None = None, performer: str | None = None, title: str | None = None, reply_markup: types.InlineKeyboardMarkup | types.ReplyKeyboardMarkup | types.ReplyKeyboardRemove | types.ForceReply | None = None, parse_mode: str | None = None, disable_notification: bool | None = None, timeout: int | float | None = None, thumbnail: str | bytes | None = None, caption_entities: list[types.MessageEntity] | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, reply_parameters: types.ReplyParameters | None = None, business_connection_id: str | None = None, message_effect_id: str | None = None, allow_paid_broadcast: bool | None = None, direct_messages_topic_id: int | None = None, suggested_post_parameters: types.SuggestedPostParameters | None = None) -> types.Message: ...
async def send_data(token: str, chat_id: str | int, data: str | bytes, data_type: str, reply_markup: types.InlineKeyboardMarkup | types.ReplyKeyboardMarkup | types.ReplyKeyboardRemove | types.ForceReply | None = None, parse_mode: str | None = None, disable_notification: bool | None = None, timeout: int | float | None = None, caption: str | None = None, thumbnail: str | bytes | None = None, caption_entities: list[types.MessageEntity] | None = None, disable_content_type_detection: bool | None = None, visible_file_name: str | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, emoji: str | None = None, reply_parameters: types.ReplyParameters | None = None, business_connection_id: str | None = None, message_effect_id: str | None = None, allow_paid_broadcast: bool | None = None, direct_messages_topic_id: int | None = None, suggested_post_parameters: types.SuggestedPostParameters | None = None) -> types.Message: ...
async def get_method_by_type(data_type: str) -> str: ...
async def ban_chat_member(token: str, chat_id: str | int, user_id: int, until_date: int | datetime.datetime | None = None, revoke_messages: bool | None = None) -> bool: ...
async def unban_chat_member(token: str, chat_id: str | int, user_id: int, only_if_banned: bool) -> bool: ...
async def restrict_chat_member(token: str, chat_id: str | int, user_id: int, permissions: types.ChatPermissions, until_date: int | datetime.datetime | None = None, use_independent_chat_permissions: bool | None = None) -> bool: ...
async def promote_chat_member(token: str, chat_id: str | int, user_id: int, can_change_info: bool | None = None, can_post_messages: bool | None = None, can_edit_messages: bool | None = None, can_delete_messages: bool | None = None, can_invite_users: bool | None = None, can_restrict_members: bool | None = None, can_pin_messages: bool | None = None, can_promote_members: bool | None = None, is_anonymous: bool | None = None, can_manage_chat: bool | None = None, can_manage_video_chats: bool | None = None, can_manage_topics: bool | None = None, can_post_stories: bool | None = None, can_edit_stories: bool | None = None, can_delete_stories: bool | None = None, can_manage_direct_messages: bool | None = None, can_manage_tags: bool | None = None) -> bool: ...
async def set_chat_administrator_custom_title(token: str, chat_id: str | int, user_id: int, custom_title: str) -> bool: ...
async def set_chat_member_tag(token: str, chat_id: str | int, user_id: int, tag: str | None = None) -> bool: ...
async def ban_chat_sender_chat(token: str, chat_id: str | int, sender_chat_id: int) -> bool: ...
async def unban_chat_sender_chat(token: str, chat_id: str | int, sender_chat_id: int) -> bool: ...
async def set_chat_permissions(token: str, chat_id: str | int, permissions: types.ChatPermissions, use_independent_chat_permissions: bool | None = None) -> bool: ...
async def create_chat_invite_link(token: str, chat_id: str | int, name: str | None = None, expire_date: int | datetime.datetime | None = None, member_limit: int | None = None, creates_join_request: bool | None = None) -> types.ChatInviteLink: ...
async def edit_chat_invite_link(token: str, chat_id: str | int, invite_link: str, name: str | None = None, expire_date: int | datetime.datetime | None = None, member_limit: int | None = None, creates_join_request: bool | None = None) -> types.ChatInviteLink: ...
async def create_chat_subscription_invite_link(token: str, chat_id: str | int, subscription_period: int, subscription_price: int, name: str | None = None) -> types.ChatInviteLink: ...
async def edit_chat_subscription_invite_link(token: str, chat_id: str | int, invite_link: str, name: str | None = None) -> types.ChatInviteLink: ...
async def revoke_chat_invite_link(token: str, chat_id: str | int, invite_link: str) -> types.ChatInviteLink: ...
async def export_chat_invite_link(token: str, chat_id: str | int) -> str: ...
async def approve_chat_join_request(token: str, chat_id: str | int, user_id: int) -> bool: ...
async def decline_chat_join_request(token: str, chat_id: str | int, user_id: int) -> bool: ...
async def set_chat_photo(token: str, chat_id: str | int, photo: str | bytes) -> bool: ...
async def delete_chat_photo(token: str, chat_id: str | int) -> bool: ...
async def set_chat_title(token: str, chat_id: str | int, title: str) -> bool: ...
async def set_my_description(token: str, description: str | None = None, language_code: str | None = None) -> bool: ...
async def get_my_description(token: str, language_code: str | None = None) -> types.BotDescription: ...
async def set_my_short_description(token: str, short_description: str | None = None, language_code: str | None = None) -> bool: ...
async def get_my_short_description(token: str, language_code: str | None = None) -> types.BotShortDescription: ...
async def get_my_commands(token: str, scope: types.BotCommandScope | None = None, language_code: str | None = None) -> list[types.BotCommand]: ...
async def set_my_name(token: str, name: str | None = None, language_code: str | None = None) -> bool: ...
async def get_my_name(token: str, language_code: str | None = None) -> types.BotName: ...
async def set_my_profile_photo(token: str, photo: str | bytes) -> bool: ...
async def remove_my_profile_photo(token: str) -> bool: ...
async def set_chat_menu_button(token: str, chat_id: int | str | None = None, menu_button: types.MenuButton | None = None) -> bool: ...
async def get_chat_menu_button(token: str, chat_id: int | str | None = None) -> types.MenuButton: ...
async def set_my_default_administrator_rights(token: str, rights: types.ChatAdministratorRights | None = None, for_channels: bool | None = None) -> bool: ...
async def get_my_default_administrator_rights(token: str, for_channels: bool | None = None) -> types.ChatAdministratorRights: ...
async def set_my_commands(token: str, commands: list[types.BotCommand], scope: types.BotCommandScope | None = None, language_code: str | None = None) -> bool: ...
async def get_business_connection(token: str, business_connection_id: str) -> types.BusinessConnection: ...
async def get_managed_bot_token(token: str, user_id: int) -> str: ...
async def replace_managed_bot_token(token: str, user_id: int) -> str: ...
async def delete_my_commands(token: str, scope: types.BotCommandScope | None = None, language_code: str | None = None) -> bool: ...
async def set_chat_description(token: str, chat_id: str | int, description: str) -> bool: ...
async def pin_chat_message(token: str, chat_id: str | int, message_id: int, disable_notification: bool | None = None, business_connection_id: str | None = None) -> bool: ...
async def unpin_chat_message(token: str, chat_id: str | int, message_id: int, business_connection_id: str | None = None) -> bool: ...
async def unpin_all_chat_messages(token: str, chat_id: str | int) -> bool: ...
async def edit_message_text(token: str, text: str, chat_id: str | int | None = None, message_id: int | None = None, inline_message_id: str | None = None, parse_mode: str | None = None, entities: list[types.MessageEntity] | None = None, reply_markup: types.InlineKeyboardMarkup | None = None, link_preview_options: types.LinkPreviewOptions | None = None, business_connection_id: str | None = None, timeout: int | float | None = None) -> types.Message | bool: ...
async def edit_message_caption(token: str, caption: str | None, chat_id: str | int | None = None, message_id: int | None = None, inline_message_id: str | None = None, parse_mode: str | None = None, caption_entities: list[types.MessageEntity] | None = None, reply_markup: types.InlineKeyboardMarkup | None = None, show_caption_above_media: bool | None = None, business_connection_id: str | None = None, timeout: int | float | None = None) -> types.Message | bool: ...
async def edit_message_media(token: str, media: types.InputMedia, chat_id: str | int | None = None, message_id: int | None = None, inline_message_id: str | None = None, reply_markup: types.InlineKeyboardMarkup | None = None, business_connection_id: str | None = None, timeout: int | float | None = None) -> types.Message | bool: ...
async def edit_message_reply_markup(token: str, chat_id: str | int | None = None, message_id: int | None = None, inline_message_id: str | None = None, reply_markup: types.InlineKeyboardMarkup | None = None, business_connection_id: str | None = None, timeout: int | float | None = None) -> types.Message | bool: ...
async def approve_suggested_post(token: str, chat_id: str | int, message_id: int, send_date: int | None = None) -> bool: ...
async def decline_suggested_post(token: str, chat_id: str | int, message_id: int, comment: str | None = None) -> bool: ...
async def delete_message(token: str, chat_id: str | int, message_id: int, timeout: int | float | None = None) -> bool: ...
async def send_game(token: str, chat_id: str | int, game_short_name: str, disable_notification: bool | None = None, reply_markup: types.InlineKeyboardMarkup | None = None, timeout: int | float | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, reply_parameters: types.ReplyParameters | None = None, business_connection_id: str | None = None, message_effect_id: str | None = None, allow_paid_broadcast: bool | None = None) -> types.Message: ...
async def set_game_score(token: str, user_id: int, score: int, force: bool | None = None, disable_edit_message: bool | None = None, chat_id: str | int | None = None, message_id: int | None = None, inline_message_id: str | None = None) -> types.Message | bool: ...
async def get_game_high_scores(token: str, user_id: int, chat_id: str | int | None = None, message_id: int | None = None, inline_message_id: str | None = None) -> list[types.GameHighScore]: ...
async def send_invoice(token: str, chat_id: str | int, title: str, description: str, invoice_payload: str, provider_token: str, currency: str, prices: list[types.LabeledPrice], start_parameter: str | None = None, photo_url: str | None = None, photo_size: int | None = None, photo_width: int | None = None, photo_height: int | None = None, need_name: bool | None = None, need_phone_number: bool | None = None, need_email: bool | None = None, need_shipping_address: bool | None = None, send_phone_number_to_provider: bool | None = None, send_email_to_provider: bool | None = None, is_flexible: bool | None = None, disable_notification: bool | None = None, reply_markup: types.InlineKeyboardMarkup | None = None, provider_data: str | None = None, timeout: int | float | None = None, max_tip_amount: int | None = None, suggested_tip_amounts: list[int] | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, reply_parameters: types.ReplyParameters | None = None, message_effect_id: str | None = None, allow_paid_broadcast: bool | None = None, direct_messages_topic_id: int | None = None, suggested_post_parameters: types.SuggestedPostParameters | None = None) -> types.Message: ...
async def answer_shipping_query(token: str, shipping_query_id: str, ok: bool, shipping_options: list[types.ShippingOption] | None = None, error_message: str | None = None) -> bool: ...
async def answer_pre_checkout_query(token: str, pre_checkout_query_id: str, ok: bool, error_message: str | None = None) -> bool: ...
async def get_my_star_balance(token: str) -> types.StarAmount: ...
async def get_star_transactions(token: str, offset: str | None = None, limit: int | None = None) -> types.StarTransactions: ...
async def refund_star_payment(token: str, user_id: int, telegram_payment_charge_id: str) -> bool: ...
async def edit_user_star_subscription(token: str, user_id: int, telegram_payment_charge_id: str, is_canceled: bool) -> bool: ...
async def unpin_all_general_forum_topic_messages(token: str, chat_id: str | int) -> bool: ...
async def answer_callback_query(token: str, callback_query_id: str, text: str | None = None, show_alert: bool | None = None, url: str | None = None, cache_time: int | None = None) -> bool: ...
async def get_user_chat_boosts(token: str, chat_id: str | int, user_id: int) -> types.UserChatBoosts: ...
async def answer_inline_query(token: str, inline_query_id: str, results: list[types.InlineQueryResultBase], cache_time: int | None = None, is_personal: bool | None = None, next_offset: int | None = None, button: types.InlineQueryResultsButton | None = None) -> bool: ...
async def get_sticker_set(token: str, name: str) -> types.StickerSet: ...
async def get_custom_emoji_stickers(token: str, custom_emoji_ids: list[str]) -> list[types.Sticker]: ...
async def set_sticker_keywords(token: str, sticker: str, keywords: list[str] | None = None) -> bool: ...
async def set_sticker_mask_position(token: str, sticker: str, mask_position: types.MaskPosition | None = None) -> bool: ...
async def upload_sticker_file(token: str, user_id: int, sticker: str | bytes, sticker_format: str) -> types.File: ...
async def set_sticker_emoji_list(token: str, sticker: str, emoji_list: list[str]) -> bool: ...
async def delete_sticker_set(token: str, name: str) -> bool: ...
async def send_gift(token: str, gift_id: str, text: str | None = None, text_parse_mode: str | None = None, text_entities: list[types.MessageEntity] | None = None, pay_for_upgrade: bool | None = None, user_id: int | None = None, chat_id: str | int | None = None) -> bool: ...
async def verify_user(token: str, user_id: int, custom_description: str | None = None) -> bool: ...
async def verify_chat(token: str, chat_id: str | int, custom_description: str | None = None) -> bool: ...
async def remove_user_verification(token: str, user_id: int) -> bool: ...
async def remove_chat_verification(token: str, chat_id: str | int) -> bool: ...
async def read_business_message(token: str, business_connection_id: str, chat_id: str | int, message_id: int) -> bool: ...
async def delete_business_messages(token: str, business_connection_id: str, message_ids: list[int]) -> bool: ...
async def set_business_account_name(token: str, business_connection_id: str, first_name: str, last_name: str | None = None) -> bool: ...
async def set_business_account_username(token: str, business_connection_id: str, username: str | None = None) -> bool: ...
async def set_business_account_bio(token: str, business_connection_id: str, bio: str | None = None) -> bool: ...
async def set_business_account_gift_settings(token: str, business_connection_id: str, show_gift_button: bool, accepted_gift_types: types.AcceptedGiftTypes) -> bool: ...
async def get_business_account_star_balance(token: str, business_connection_id: str) -> types.StarAmount: ...
async def transfer_business_account_stars(token: str, business_connection_id: str, star_count: int) -> types.StarTransactions: ...
async def get_business_account_gifts(token: str, business_connection_id: str, exclude_unsaved: bool | None = None, exclude_saved: bool | None = None, exclude_unlimited: bool | None = None, exclude_unique: bool | None = None, sort_by_price: bool | None = None, offset: int | None = None, limit: int | None = None, exclude_limited_upgradable: bool | None = None, exclude_limited_non_upgradable: bool | None = None, exclude_from_blockchain: bool | None = None) -> types.Gifts: ...
async def get_user_gifts(token: str, user_id: int, exclude_unlimited: bool | None = None, exclude_limited_upgradable: bool | None = None, exclude_limited_non_upgradable: bool | None = None, exclude_from_blockchain: bool | None = None, exclude_unique: bool | None = None, sort_by_price: bool | None = None, offset: int | None = None, limit: int | None = None) -> types.Gifts: ...
async def get_chat_gifts(token: str, chat_id: str | int, exclude_unsaved: bool | None = None, exclude_saved: bool | None = None, exclude_unlimited: bool | None = None, exclude_limited_upgradable: bool | None = None, exclude_limited_non_upgradable: bool | None = None, exclude_from_blockchain: bool | None = None, exclude_unique: bool | None = None, sort_by_price: bool | None = None, offset: int | None = None, limit: int | None = None) -> types.Gifts: ...
async def convert_gift_to_stars(token: str, business_connection_id: str, owned_gift_id: int) -> int: ...
async def upgrade_gift(token: str, business_connection_id: str, owned_gift_id: int, keep_original_details: bool | None = None, star_count: int | None = None) -> types.Gift: ...
async def transfer_gift(token: str, business_connection_id: str, owned_gift_id: int, new_owner_chat_id: str | int, star_count: int | None = None) -> bool: ...
async def post_story(token: str, business_connection_id: str, content: types.InputStoryContent, active_period: int, caption: str | None = None, parse_mode: str | None = None, caption_entities: list[types.MessageEntity] | None = None, areas: list[types.StoryArea] | None = None, post_to_chat_page: bool | None = None, protect_content: bool | None = None) -> types.Message | bool: ...
async def repost_story(token: str, business_connection_id: str, from_chat_id: str | int, from_story_id: int, active_period: int, post_to_chat_page: bool | None = None, protect_content: bool | None = None) -> types.Message: ...
async def edit_story(token: str, business_connection_id: str, story_id: int, content: types.InputStoryContent, caption: str | None = None, parse_mode: str | None = None, caption_entities: list[types.MessageEntity] | None = None, areas: list[types.StoryArea] | None = None) -> bool: ...
async def delete_story(token: str, business_connection_id: str, story_id: int) -> bool: ...
async def gift_premium_subscription(token: str, user_id: int, month_count: int, star_count: int, text: str | None = None, text_parse_mode: str | None = None, text_entities: list[types.MessageEntity] | None = None) -> bool: ...
async def set_business_account_profile_photo(token: str, business_connection_id: str, photo: str | bytes, is_public: bool | None = None) -> bool: ...
async def remove_business_account_profile_photo(token: str, business_connection_id: str, is_public: bool | None = None) -> bool: ...
async def get_available_gifts(token: str) -> types.Gifts: ...
async def set_custom_emoji_sticker_set_thumbnail(token: str, name: str, custom_emoji_id: str | None = None) -> bool: ...
async def set_sticker_set_title(token: str, name: str, title: str) -> bool: ...
async def create_new_sticker_set(token: str, user_id: int, name: str, title: str, stickers: list[types.InputSticker], sticker_type: str | None = None, needs_repainting: bool | None = None) -> bool: ...
async def add_sticker_to_set(token: str, user_id: int, name: str, sticker: types.InputSticker) -> bool: ...
async def set_sticker_position_in_set(token: str, sticker: str, position: int) -> bool: ...
async def delete_sticker_from_set(token: str, sticker: str) -> bool: ...
async def create_invoice_link(token: str, title: str, description: str, payload: str, provider_token: str, currency: str, prices: list[types.LabeledPrice], max_tip_amount: int | None = None, suggested_tip_amounts: list[int] | None = None, provider_data: str | None = None, photo_url: str | None = None, photo_size: int | None = None, photo_width: int | None = None, photo_height: int | None = None, need_name: bool | None = None, need_phone_number: bool | None = None, need_email: bool | None = None, need_shipping_address: bool | None = None, send_phone_number_to_provider: bool | None = None, send_email_to_provider: bool | None = None, is_flexible: bool | None = None, subscription_period: int | None = None, business_connection_id: str | None = None) -> str: ...
async def send_poll(token: str, chat_id: str | int, question: str, options: list[str], is_anonymous: bool | None = None, type: str | None = None, allows_multiple_answers: bool | None = None, explanation: str | None = None, explanation_parse_mode: str | None = None, open_period: int | None = None, close_date: int | datetime.datetime | None = None, is_closed: bool | None = None, disable_notification: bool = False, reply_markup: types.InlineKeyboardMarkup | types.ReplyKeyboardMarkup | types.ReplyKeyboardRemove | types.ForceReply | None = None, timeout: int | float | None = None, explanation_entities: list[types.MessageEntity] | None = None, protect_content: bool | None = None, message_thread_id: int | None = None, reply_parameters: types.ReplyParameters | None = None, business_connection_id: str | None = None, question_parse_mode: str | None = None, question_entities: list[types.MessageEntity] | None = None, message_effect_id: str | None = None, allow_paid_broadcast: bool | None = None, allows_revoting: bool | None = None, shuffle_options: bool | None = None, allow_adding_options: bool | None = None, hide_results_until_closes: bool | None = None, correct_option_ids: list[int] | None = None, description: str | None = None, description_parse_mode: str | None = None, description_entities: list[types.MessageEntity] | None = None) -> types.Message: ...
async def create_forum_topic(token: str, chat_id: str | int, name: str, icon_color: int | None = None, icon_custom_emoji_id: str | None = None) -> types.ForumTopic: ...
async def edit_forum_topic(token: str, chat_id: str | int, message_thread_id: int, name: str | None = None, icon_custom_emoji_id: str | None = None) -> bool: ...
async def close_forum_topic(token: str, chat_id: str | int, message_thread_id: int) -> bool: ...
async def reopen_forum_topic(token: str, chat_id: str | int, message_thread_id: int) -> bool: ...
async def delete_forum_topic(token: str, chat_id: str | int, message_thread_id: int) -> bool: ...
async def unpin_all_forum_topic_messages(token: str, chat_id: str | int, message_thread_id: int) -> bool: ...
async def get_forum_topic_icon_stickers(token: str) -> list[types.Sticker]: ...
async def edit_general_forum_topic(token: str, chat_id: str | int, name: str) -> bool: ...
async def close_general_forum_topic(token: str, chat_id: str | int) -> bool: ...
async def reopen_general_forum_topic(token: str, chat_id: str | int) -> bool: ...
async def hide_general_forum_topic(token: str, chat_id: str | int) -> bool: ...
async def unhide_general_forum_topic(token: str, chat_id: str | int) -> bool: ...
async def delete_messages(token: str, chat_id: str | int, message_ids: list[int]) -> bool: ...
async def forward_messages(token: str, chat_id: str | int, from_chat_id: str | int, message_ids: list[int], disable_notification: bool | None = None, message_thread_id: int | None = None, protect_content: bool | None = None, direct_messages_topic_id: int | None = None) -> list[types.MessageID]: ...
async def copy_messages(token: str, chat_id: str | int, from_chat_id: str | int, message_ids: list[int], disable_notification: bool | None = None, message_thread_id: int | None = None, protect_content: bool | None = None, remove_caption: bool | None = None, direct_messages_topic_id: int | None = None) -> list[types.MessageID]: ...
async def convert_input_media(media: types.InputMedia | dict[str, Any]) -> types.InputMedia: ...
async def convert_input_media_array(array: list[types.InputMedia | dict[str, Any]]) -> list[types.InputMedia]: ...
async def stop_poll(token: str, chat_id: str | int, message_id: int, reply_markup: types.InlineKeyboardMarkup | None = None, business_connection_id: str | None = None) -> types.Poll: ...

class ApiException(Exception):
    function_name: str
    result: Any

    def __init__(self, msg: str, function_name: str, result: Any) -> None: ...

class ApiHTTPException(ApiException):
    result: aiohttp.ClientResponse

    def __init__(self, function_name: str, result: aiohttp.ClientResponse) -> None: ...

class ApiInvalidJSONException(ApiException):
    result: str

    def __init__(self, function_name: str, result: str) -> None: ...

class ApiTelegramException(ApiException):
    result_json: dict[str, Any]
    error_code: int
    description: str

    def __init__(self, function_name: str, result: Any, result_json: dict[str, Any]) -> None: ...

class RequestTimeout(Exception): ...
