from telebot.states import State as State, StatesGroup as StatesGroup

class BaseMiddleware:
    update_sensitive: bool
    def __init__(self) -> None: ...
    async def pre_process(self, message, data) -> None: ...
    async def post_process(self, message, data, exception) -> None: ...

class SkipHandler:
    def __init__(self) -> None: ...

class CancelUpdate:
    def __init__(self) -> None: ...

class ContinueHandling:
    def __init__(self) -> None: ...
