import aiohttp
from _typeshed import Incomplete
from telebot import types as types, util as util

API_URL: str
logger: Incomplete
proxy: Incomplete
session: Incomplete
FILE_URL: Incomplete
REQUEST_TIMEOUT: int
MAX_RETRIES: int
REQUEST_LIMIT: int

class SessionManager:
    ssl_context: Incomplete
    def __init__(self) -> None: ...
    @property
    def session(self): ...
    @session.setter
    def session(self, value) -> None: ...
    async def create_session(self): ...
    async def get_session(self): ...

session_manager: Incomplete

async def get_me(token): ...
async def log_out(token): ...
async def close(token): ...
async def get_file(token, file_id): ...
async def get_file_url(token, file_id): ...
async def download_file(token, file_path): ...
async def set_webhook(token, url=None, certificate=None, max_connections=None, allowed_updates=None, ip_address=None, drop_pending_updates=None, timeout=None, secret_token=None): ...
async def delete_webhook(token, drop_pending_updates=None, timeout=None): ...
async def get_webhook_info(token, timeout=None): ...
async def get_updates(token, offset=None, limit=None, timeout=None, allowed_updates=None, request_timeout=None): ...
async def send_message(token, chat_id, text, reply_markup=None, parse_mode=None, disable_notification=None, timeout=None, entities=None, protect_content=None, message_thread_id=None, reply_parameters=None, link_preview_options=None, business_connection_id=None, message_effect_id=None, allow_paid_broadcast=None, direct_messages_topic_id=None, suggested_post_parameters=None): ...
async def get_user_profile_photos(token, user_id, offset=None, limit=None): ...
async def get_user_profile_audios(token, user_id, offset=None, limit=None): ...
async def set_user_emoji_status(token, user_id, emoji_status_custom_emoji_id=None, emoji_status_expiration_date=None): ...
async def set_message_reaction(token, chat_id, message_id, reaction=None, is_big=None): ...
async def get_chat(token, chat_id): ...
async def leave_chat(token, chat_id): ...
async def get_chat_administrators(token, chat_id): ...
async def get_chat_member_count(token, chat_id): ...
async def replace_sticker_in_set(token, user_id, name, old_sticker, sticker): ...
async def set_sticker_set_thumbnail(token, name, user_id, thumbnail, format): ...
async def set_chat_sticker_set(token, chat_id, sticker_set_name): ...
async def delete_chat_sticker_set(token, chat_id): ...
async def answer_web_app_query(token, web_app_query_id, result: types.InlineQueryResultBase): ...
async def save_prepared_inline_message(token, user_id, result: types.InlineQueryResultBase, allow_user_chats=None, allow_bot_chats=None, allow_group_chats=None, allow_channel_chats=None): ...
async def save_prepared_keyboard_button(token, user_id, button: types.KeyboardButton): ...
async def get_chat_member(token, chat_id, user_id): ...
async def forward_message(token, chat_id, from_chat_id, message_id, disable_notification=None, timeout=None, protect_content=None, message_thread_id=None, video_start_timestamp=None, direct_messages_topic_id=None, suggested_post_parameters=None, message_effect_id=None): ...
async def copy_message(token, chat_id, from_chat_id, message_id, caption=None, parse_mode=None, caption_entities=None, disable_notification=None, reply_markup=None, timeout=None, protect_content=None, message_thread_id=None, reply_parameters=None, show_caption_above_media=None, allow_paid_broadcast=None, video_start_timestamp=None, direct_messages_topic_id=None, suggested_post_parameters=None, message_effect_id=None): ...
async def send_checklist(token, business_connection_id, chat_id, checklist, disable_notification=None, protect_content=None, message_effect_id=None, reply_parameters=None, reply_markup=None): ...
async def edit_message_checklist(token, business_connection_id, chat_id, message_id, checklist, reply_markup=None): ...
async def send_dice(token, chat_id, emoji=None, disable_notification=None, reply_markup=None, timeout=None, protect_content=None, message_thread_id=None, reply_parameters=None, business_connection_id=None, message_effect_id=None, allow_paid_broadcast=None, direct_messages_topic_id=None, suggested_post_parameters=None): ...
async def send_photo(token, chat_id, photo, caption=None, reply_markup=None, parse_mode=None, disable_notification=None, timeout=None, caption_entities=None, protect_content=None, message_thread_id=None, has_spoiler=None, reply_parameters=None, business_connection_id=None, message_effect_id=None, show_caption_above_media=None, allow_paid_broadcast=None, direct_messages_topic_id=None, suggested_post_parameters=None): ...
async def send_paid_media(token, chat_id, star_count, media, caption=None, parse_mode=None, caption_entities=None, show_caption_above_media=None, disable_notification=None, protect_content=None, reply_parameters=None, reply_markup=None, business_connection_id=None, payload=None, allow_paid_broadcast=None, direct_messages_topic_id=None, suggested_post_parameters=None): ...
async def send_media_group(token, chat_id, media, disable_notification=None, timeout=None, protect_content=None, message_thread_id=None, reply_parameters=None, business_connection_id=None, message_effect_id=None, allow_paid_broadcast=None, direct_messages_topic_id=None): ...
async def send_location(token, chat_id, latitude, longitude, live_period=None, reply_markup=None, disable_notification=None, timeout=None, horizontal_accuracy=None, heading=None, proximity_alert_radius=None, protect_content=None, message_thread_id=None, reply_parameters=None, business_connection_id=None, message_effect_id=None, allow_paid_broadcast=None, direct_messages_topic_id=None, suggested_post_parameters=None): ...
async def edit_message_live_location(token, latitude, longitude, chat_id=None, message_id=None, inline_message_id=None, reply_markup=None, timeout=None, horizontal_accuracy=None, heading=None, proximity_alert_radius=None, live_period=None, business_connection_id=None): ...
async def stop_message_live_location(token, chat_id=None, message_id=None, inline_message_id=None, reply_markup=None, timeout=None, business_connection_id=None): ...
async def send_venue(token, chat_id, latitude, longitude, title, address, foursquare_id=None, foursquare_type=None, disable_notification=None, reply_markup=None, timeout=None, google_place_id=None, google_place_type=None, protect_content=None, message_thread_id=None, reply_parameters=None, business_connection_id=None, message_effect_id=None, allow_paid_broadcast=None, direct_messages_topic_id=None, suggested_post_parameters=None): ...
async def send_contact(token, chat_id, phone_number, first_name, last_name=None, vcard=None, disable_notification=None, reply_markup=None, timeout=None, protect_content=None, message_thread_id=None, reply_parameters=None, business_connection_id=None, message_effect_id=None, allow_paid_broadcast=None, direct_messages_topic_id=None, suggested_post_parameters=None): ...
async def send_message_draft(token, chat_id, draft_id, text, message_thread_id=None, parse_mode=None, entities=None): ...
async def send_chat_action(token, chat_id, action, timeout=None, message_thread_id=None, business_connection_id=None): ...
async def send_video(token, chat_id, data, duration=None, caption=None, reply_markup=None, parse_mode=None, supports_streaming=None, disable_notification=None, timeout=None, thumbnail=None, width=None, height=None, caption_entities=None, protect_content=None, message_thread_id=None, has_spoiler=None, reply_parameters=None, business_connection_id=None, message_effect_id=None, show_caption_above_media=None, allow_paid_broadcast=None, cover=None, start_timestamp=None, direct_messages_topic_id=None, suggested_post_parameters=None): ...
async def send_animation(token, chat_id, data, duration=None, caption=None, reply_markup=None, parse_mode=None, disable_notification=None, timeout=None, thumbnail=None, caption_entities=None, width=None, height=None, protect_content=None, message_thread_id=None, has_spoiler=None, reply_parameters=None, business_connection_id=None, message_effect_id=None, show_caption_above_media=None, allow_paid_broadcast=None, direct_messages_topic_id=None, suggested_post_parameters=None): ...
async def send_voice(token, chat_id, voice, caption=None, duration=None, reply_markup=None, parse_mode=None, disable_notification=None, timeout=None, caption_entities=None, protect_content=None, message_thread_id=None, reply_parameters=None, business_connection_id=None, message_effect_id=None, allow_paid_broadcast=None, direct_messages_topic_id=None, suggested_post_parameters=None): ...
async def send_video_note(token, chat_id, data, duration=None, length=None, reply_markup=None, disable_notification=None, timeout=None, thumbnail=None, protect_content=None, message_thread_id=None, reply_parameters=None, business_connection_id=None, message_effect_id=None, allow_paid_broadcast=None, direct_messages_topic_id=None, suggested_post_parameters=None): ...
async def send_audio(token, chat_id, audio, caption=None, duration=None, performer=None, title=None, reply_markup=None, parse_mode=None, disable_notification=None, timeout=None, thumbnail=None, caption_entities=None, protect_content=None, message_thread_id=None, reply_parameters=None, business_connection_id=None, message_effect_id=None, allow_paid_broadcast=None, direct_messages_topic_id=None, suggested_post_parameters=None): ...
async def send_data(token, chat_id, data, data_type, reply_markup=None, parse_mode=None, disable_notification=None, timeout=None, caption=None, thumbnail=None, caption_entities=None, disable_content_type_detection=None, visible_file_name=None, protect_content=None, message_thread_id=None, emoji=None, reply_parameters=None, business_connection_id=None, message_effect_id=None, allow_paid_broadcast=None, direct_messages_topic_id=None, suggested_post_parameters=None): ...
async def get_method_by_type(data_type): ...
async def ban_chat_member(token, chat_id, user_id, until_date=None, revoke_messages=None): ...
async def unban_chat_member(token, chat_id, user_id, only_if_banned): ...
async def restrict_chat_member(token, chat_id, user_id, permissions, until_date=None, use_independent_chat_permissions=None): ...
async def promote_chat_member(token, chat_id, user_id, can_change_info=None, can_post_messages=None, can_edit_messages=None, can_delete_messages=None, can_invite_users=None, can_restrict_members=None, can_pin_messages=None, can_promote_members=None, is_anonymous=None, can_manage_chat=None, can_manage_video_chats=None, can_manage_topics=None, can_post_stories=None, can_edit_stories=None, can_delete_stories=None, can_manage_direct_messages=None, can_manage_tags=None): ...
async def set_chat_administrator_custom_title(token, chat_id, user_id, custom_title): ...
async def set_chat_member_tag(token, chat_id, user_id, tag=None): ...
async def ban_chat_sender_chat(token, chat_id, sender_chat_id): ...
async def unban_chat_sender_chat(token, chat_id, sender_chat_id): ...
async def set_chat_permissions(token, chat_id, permissions, use_independent_chat_permissions=None): ...
async def create_chat_invite_link(token, chat_id, name, expire_date, member_limit, creates_join_request): ...
async def edit_chat_invite_link(token, chat_id, invite_link, name, expire_date, member_limit, creates_join_request): ...
async def create_chat_subscription_invite_link(token, chat_id, subscription_period, subscription_price, name=None): ...
async def edit_chat_subscription_invite_link(token, chat_id, invite_link, name=None): ...
async def revoke_chat_invite_link(token, chat_id, invite_link): ...
async def export_chat_invite_link(token, chat_id): ...
async def approve_chat_join_request(token, chat_id, user_id): ...
async def decline_chat_join_request(token, chat_id, user_id): ...
async def set_chat_photo(token, chat_id, photo): ...
async def delete_chat_photo(token, chat_id): ...
async def set_chat_title(token, chat_id, title): ...
async def set_my_description(token, description=None, language_code=None): ...
async def get_my_description(token, language_code=None): ...
async def set_my_short_description(token, short_description=None, language_code=None): ...
async def get_my_short_description(token, language_code=None): ...
async def get_my_commands(token, scope=None, language_code=None): ...
async def set_my_name(token, name=None, language_code=None): ...
async def get_my_name(token, language_code=None): ...
async def set_my_profile_photo(token, photo): ...
async def remove_my_profile_photo(token): ...
async def set_chat_menu_button(token, chat_id=None, menu_button=None): ...
async def get_chat_menu_button(token, chat_id=None): ...
async def set_my_default_administrator_rights(token, rights=None, for_channels=None): ...
async def get_my_default_administrator_rights(token, for_channels=None): ...
async def set_my_commands(token, commands, scope=None, language_code=None): ...
async def get_business_connection(token, business_connection_id): ...
async def get_managed_bot_token(token, user_id): ...
async def replace_managed_bot_token(token, user_id): ...
async def delete_my_commands(token, scope=None, language_code=None): ...
async def set_chat_description(token, chat_id, description): ...
async def pin_chat_message(token, chat_id, message_id, disable_notification=None, business_connection_id=None): ...
async def unpin_chat_message(token, chat_id, message_id, business_connection_id=None): ...
async def unpin_all_chat_messages(token, chat_id): ...
async def edit_message_text(token, text, chat_id=None, message_id=None, inline_message_id=None, parse_mode=None, entities=None, reply_markup=None, link_preview_options=None, business_connection_id=None, timeout=None): ...
async def edit_message_caption(token, caption, chat_id=None, message_id=None, inline_message_id=None, parse_mode=None, caption_entities=None, reply_markup=None, show_caption_above_media=None, business_connection_id=None, timeout=None): ...
async def edit_message_media(token, media, chat_id=None, message_id=None, inline_message_id=None, reply_markup=None, business_connection_id=None, timeout=None): ...
async def edit_message_reply_markup(token, chat_id=None, message_id=None, inline_message_id=None, reply_markup=None, business_connection_id=None, timeout=None): ...
async def approve_suggested_post(token, chat_id, message_id, send_date=None): ...
async def decline_suggested_post(token, chat_id, message_id, comment=None): ...
async def delete_message(token, chat_id, message_id, timeout=None): ...
async def send_game(token, chat_id, game_short_name, disable_notification=None, reply_markup=None, timeout=None, protect_content=None, message_thread_id=None, reply_parameters=None, business_connection_id=None, message_effect_id=None, allow_paid_broadcast=None): ...
async def set_game_score(token, user_id, score, force=None, disable_edit_message=None, chat_id=None, message_id=None, inline_message_id=None): ...
async def get_game_high_scores(token, user_id, chat_id=None, message_id=None, inline_message_id=None): ...
async def send_invoice(token, chat_id, title, description, invoice_payload, provider_token, currency, prices, start_parameter=None, photo_url=None, photo_size=None, photo_width=None, photo_height=None, need_name=None, need_phone_number=None, need_email=None, need_shipping_address=None, send_phone_number_to_provider=None, send_email_to_provider=None, is_flexible=None, disable_notification=None, reply_markup=None, provider_data=None, timeout=None, max_tip_amount=None, suggested_tip_amounts=None, protect_content=None, message_thread_id=None, reply_parameters=None, message_effect_id=None, allow_paid_broadcast=None, direct_messages_topic_id=None, suggested_post_parameters=None): ...
async def answer_shipping_query(token, shipping_query_id, ok, shipping_options=None, error_message=None): ...
async def answer_pre_checkout_query(token, pre_checkout_query_id, ok, error_message=None): ...
async def get_my_star_balance(token): ...
async def get_star_transactions(token, offset=None, limit=None): ...
async def refund_star_payment(token, user_id, telegram_payment_charge_id): ...
async def edit_user_star_subscription(token, user_id, telegram_payment_charge_id, is_canceled): ...
async def unpin_all_general_forum_topic_messages(token, chat_id): ...
async def answer_callback_query(token, callback_query_id, text=None, show_alert=None, url=None, cache_time=None): ...
async def get_user_chat_boosts(token, chat_id, user_id): ...
async def answer_inline_query(token, inline_query_id, results, cache_time=None, is_personal=None, next_offset=None, button=None): ...
async def get_sticker_set(token, name): ...
async def get_custom_emoji_stickers(token, custom_emoji_ids): ...
async def set_sticker_keywords(token, sticker, keywords=None): ...
async def set_sticker_mask_position(token, sticker, mask_position=None): ...
async def upload_sticker_file(token, user_id, sticker, sticker_format): ...
async def set_sticker_emoji_list(token, sticker, emoji_list): ...
async def delete_sticker_set(token, name): ...
async def send_gift(token, gift_id, text=None, text_parse_mode=None, text_entities=None, pay_for_upgrade=None, user_id=None, chat_id=None): ...
async def verify_user(token, user_id, custom_description=None): ...
async def verify_chat(token, chat_id, custom_description=None): ...
async def remove_user_verification(token, user_id): ...
async def remove_chat_verification(token, chat_id): ...
async def read_business_message(token, business_connection_id, chat_id, message_id): ...
async def delete_business_messages(token, business_connection_id, message_ids): ...
async def set_business_account_name(token, business_connection_id, first_name, last_name=None): ...
async def set_business_account_username(token, business_connection_id, username=None): ...
async def set_business_account_bio(token, business_connection_id, bio=None): ...
async def set_business_account_gift_settings(token, business_connection_id, show_gift_button, accepted_gift_types): ...
async def get_business_account_star_balance(token, business_connection_id): ...
async def transfer_business_account_stars(token, business_connection_id, star_count): ...
async def get_business_account_gifts(token, business_connection_id, exclude_unsaved=None, exclude_saved=None, exclude_unlimited=None, exclude_unique=None, sort_by_price=None, offset=None, limit=None, exclude_limited_upgradable=None, exclude_limited_non_upgradable=None, exclude_from_blockchain=None): ...
async def get_user_gifts(token, user_id, exclude_unlimited=None, exclude_limited_upgradable=None, exclude_limited_non_upgradable=None, exclude_from_blockchain=None, exclude_unique=None, sort_by_price=None, offset=None, limit=None): ...
async def get_chat_gifts(token, chat_id, exclude_unsaved=None, exclude_saved=None, exclude_unlimited=None, exclude_limited_upgradable=None, exclude_limited_non_upgradable=None, exclude_from_blockchain=None, exclude_unique=None, sort_by_price=None, offset=None, limit=None): ...
async def convert_gift_to_stars(token, business_connection_id, owned_gift_id): ...
async def upgrade_gift(token, business_connection_id, owned_gift_id, keep_original_details=None, star_count=None): ...
async def transfer_gift(token, business_connection_id, owned_gift_id, new_owner_chat_id, star_count=None): ...
async def post_story(token, business_connection_id, content, active_period, caption=None, parse_mode=None, caption_entities=None, areas=None, post_to_chat_page=None, protect_content=None): ...
async def repost_story(token, business_connection_id, from_chat_id, from_story_id, active_period, post_to_chat_page=None, protect_content=None): ...
async def edit_story(token, business_connection_id, story_id, content, caption=None, parse_mode=None, caption_entities=None, areas=None): ...
async def delete_story(token, business_connection_id, story_id): ...
async def gift_premium_subscription(token, user_id, month_count, star_count, text=None, text_parse_mode=None, text_entities=None): ...
async def set_business_account_profile_photo(token, business_connection_id, photo, is_public=None): ...
async def remove_business_account_profile_photo(token, business_connection_id, is_public=None): ...
async def get_available_gifts(token): ...
async def set_custom_emoji_sticker_set_thumbnail(token, name, custom_emoji_id=None): ...
async def set_sticker_set_title(token, name, title): ...
async def create_new_sticker_set(token, user_id, name, title, stickers, sticker_type=None, needs_repainting=None): ...
async def add_sticker_to_set(token, user_id, name, sticker): ...
async def set_sticker_position_in_set(token, sticker, position): ...
async def delete_sticker_from_set(token, sticker): ...
async def create_invoice_link(token, title, description, payload, provider_token, currency, prices, max_tip_amount=None, suggested_tip_amounts=None, provider_data=None, photo_url=None, photo_size=None, photo_width=None, photo_height=None, need_name=None, need_phone_number=None, need_email=None, need_shipping_address=None, send_phone_number_to_provider=None, send_email_to_provider=None, is_flexible=None, subscription_period=None, business_connection_id=None): ...
async def send_poll(token, chat_id, question, options, is_anonymous=None, type=None, allows_multiple_answers=None, explanation=None, explanation_parse_mode=None, open_period=None, close_date=None, is_closed=None, disable_notification: bool = False, reply_markup=None, timeout=None, explanation_entities=None, protect_content=None, message_thread_id=None, reply_parameters=None, business_connection_id=None, question_parse_mode=None, question_entities=None, message_effect_id=None, allow_paid_broadcast=None, allows_revoting=None, shuffle_options=None, allow_adding_options=None, hide_results_until_closes=None, correct_option_ids=None, description=None, description_parse_mode=None, description_entities=None): ...
async def create_forum_topic(token, chat_id, name, icon_color=None, icon_custom_emoji_id=None): ...
async def edit_forum_topic(token, chat_id, message_thread_id, name=None, icon_custom_emoji_id=None): ...
async def close_forum_topic(token, chat_id, message_thread_id): ...
async def reopen_forum_topic(token, chat_id, message_thread_id): ...
async def delete_forum_topic(token, chat_id, message_thread_id): ...
async def unpin_all_forum_topic_messages(token, chat_id, message_thread_id): ...
async def get_forum_topic_icon_stickers(token): ...
async def edit_general_forum_topic(token, chat_id, name): ...
async def close_general_forum_topic(token, chat_id): ...
async def reopen_general_forum_topic(token, chat_id): ...
async def hide_general_forum_topic(token, chat_id): ...
async def unhide_general_forum_topic(token, chat_id): ...
async def delete_messages(token, chat_id, message_ids): ...
async def forward_messages(token, chat_id, from_chat_id, message_ids, disable_notification=None, message_thread_id=None, protect_content=None, direct_messages_topic_id=None): ...
async def copy_messages(token, chat_id, from_chat_id, message_ids, disable_notification=None, message_thread_id=None, protect_content=None, remove_caption=None, direct_messages_topic_id=None): ...
async def convert_input_media(media): ...
async def convert_input_media_array(array): ...
async def stop_poll(token, chat_id, message_id, reply_markup=None, business_connection_id=None): ...

class ApiException(Exception):
    function_name: Incomplete
    result: Incomplete
    def __init__(self, msg, function_name, result) -> None: ...

class ApiHTTPException(ApiException):
    def __init__(self, function_name, result: aiohttp.ClientResponse) -> None: ...

class ApiInvalidJSONException(ApiException):
    def __init__(self, function_name, result) -> None: ...

class ApiTelegramException(ApiException):
    result_json: Incomplete
    error_code: Incomplete
    description: Incomplete
    def __init__(self, function_name, result, result_json) -> None: ...

class RequestTimeout(Exception): ...
