from telebot.states import State as State, StatesGroup as StatesGroup
from typing import Any

class BaseMiddleware:
    update_sensitive: bool
    def __init__(self) -> None: ...
    async def pre_process(self, message: Any, data: Any) -> None: ...
    async def post_process(self, message: Any, data: Any, exception: Any) -> None: ...

class SkipHandler:
    def __init__(self) -> None: ...

class CancelUpdate:
    def __init__(self) -> None: ...

class ContinueHandling:
    def __init__(self) -> None: ...
