from telebot import types
class CallbackDataFilter:
    config: dict[str, str]
    factory: CallbackData
    def __init__(self, factory: CallbackData, config: dict[str, str]) -> None: ...
    def check(self, query: types.CallbackQuery) -> bool: ...

class CallbackData:
    prefix: str
    sep: str
    def __init__(self, *parts: str, prefix: str, sep: str = ':') -> None: ...
    def new(self, *args: str, **kwargs: str) -> str: ...
    def parse(self, callback_data: str) -> dict[str, str]: ...
    def filter(self, **config: str) -> CallbackDataFilter: ...
