from telebot import apihelper as apihelper
from telebot.states import State as State, StatesGroup as StatesGroup
from typing import Any, TypeAlias
from redis import Redis
import threading

redis_installed: bool

_HandlerDict: TypeAlias = dict[Any, list[Any]]

class HandlerBackend:
    handlers: _HandlerDict
    def __init__(self, handlers: _HandlerDict | None = None) -> None: ...
    def register_handler(self, handler_group_id: int, handler: _HandlerDict) -> None: ...
    def clear_handlers(self, handler_group_id: int) -> None: ...
    def get_handlers(self, handler_group_id: int) -> Any: ...

class MemoryHandlerBackend(HandlerBackend):
    def register_handler(self, handler_group_id: int, handler: _HandlerDict) -> None: ...
    def clear_handlers(self, handler_group_id: int) -> None: ...
    def get_handlers(self, handler_group_id: int) -> Any: ...
    def load_handlers(self, filename: str, del_file_after_loading: bool) -> None: ...

class FileHandlerBackend(HandlerBackend):
    filename: str
    delay: int
    timer: threading.Timer
    def __init__(self, handlers: _HandlerDict | None = None, filename: str = './.handler-saves/handlers.save', delay: int = 120) -> None: ...
    def register_handler(self, handler_group_id: int, handler: _HandlerDict) -> None: ...
    def clear_handlers(self, handler_group_id: int) -> None: ...
    def get_handlers(self, handler_group_id: int) -> _HandlerDict: ...
    def start_save_timer(self) -> None: ...
    def save_handlers(self) -> None: ...
    def load_handlers(self, filename: str | None = None, del_file_after_loading: bool = True) -> None: ...
    @staticmethod
    def dump_handlers(handlers: _HandlerDict, filename: str, file_mode: str = 'wb') -> None: ...
    @staticmethod
    def return_load_handlers(filename: str, del_file_after_loading: bool = True) -> Any | None: ...

class RedisHandlerBackend(HandlerBackend):
    prefix: str
    redis: Redis
    def __init__(self, handlers: _HandlerDict | None = None, host: str = 'localhost', port: int = 6379, db: int = 0, prefix: str = 'telebot', password: str | None = None) -> None: ...
    def register_handler(self, handler_group_id: int, handler: _HandlerDict) -> None: ...
    def clear_handlers(self, handler_group_id: int) -> None: ...
    def get_handlers(self, handler_group_id: int) -> _HandlerDict: ...

# base class, use Any
class BaseMiddleware:
    update_sensitive: bool
    def __init__(self) -> None: ...
    def pre_process(self, message: Any, data: Any) -> None: ...
    def post_process(self, message: Any, data: Any, exception: Any) -> None: ...

class SkipHandler:
    def __init__(self) -> None: ...

class CancelUpdate:
    def __init__(self) -> None: ...

class ContinueHandling:
    def __init__(self) -> None: ...
