from collections.abc import Generator
from typing import TypeVar

from PIL import Image
from io import BytesIO
_T = TypeVar('_T')

pil_imported: bool

def is_string(var: Any) -> bool: ...
def is_dict(var: Any) -> bool: ...
def is_bytes(var: Any) -> bool: ...
def is_pil_image(var: Any) -> bool: ...
def pil_image_to_file(image: Image, extension: str = 'JPEG', quality: str = 'web_low') -> BytesIO: ...
def chunks(lst: list[_T], n: int) -> Generator[list[_T], None, None]: ...
def generate_random_token() -> str: ...
