from __future__ import annotations

import threading
from telebot import types
from telebot.service_utils import chunks as chunks, generate_random_token as generate_random_token, is_bytes as is_bytes, is_dict as is_dict, is_pil_image as is_pil_image, is_string as is_string, pil_image_to_file as pil_image_to_file
from typing import Any, Callable, TypeVar
from types import TracebackType

from telebot import TeleBot
from telebot.async_telebot import AsyncTeleBot
from flask import Request

import queue as Queue

__all__ = ['content_type_media', 'content_type_service', 'update_types', 'WorkerThread', 'AsyncTask', 'CustomRequestResponse', 'async_dec', 'deprecated', 'is_bytes', 'is_string', 'is_dict', 'is_pil_image', 'chunks', 'generate_random_token', 'pil_image_to_file', 'is_command', 'extract_command', 'extract_arguments', 'split_string', 'smart_split', 'escape', 'user_link', 'quick_markup', 'antiflood', 'parse_web_app_data', 'validate_web_app_data', 'or_set', 'or_clear', 'orify', 'OrEvent', 'per_thread', 'webhook_google_functions', 'validate_token', 'extract_bot_id']

content_type_media: list[str]
content_type_service: list[str]
update_types: list[str]

_EXC_INFO = tuple[type[BaseException], BaseException, TracebackType]
_T = TypeVar('_T', bound=Callable[..., Any])
_TK = TypeVar('_TK')

class WorkerThread(threading.Thread):
    count: int
    queue: Queue.Queue[tuple[Callable[..., Any], tuple[Any, ...], dict[str, Any]]]
    daemon: bool
    received_task_event: threading.Event
    done_event: threading.Event
    exception_event: threading.Event
    continue_event: threading.Event
    exception_callback: Callable[..., Any] | None
    exception_info: _EXC_INFO | None
    def __init__(self, exception_callback: Callable[..., Any] | None = None, queue: Queue.Queue[tuple[Callable[..., Any], tuple[Any, ...], dict[str, Any]]] | None = None, name: str | None = None) -> None: ...
    def run(self) -> None: ...
    def put(self, task: Callable[..., Any], *args: Any, **kwargs: Any) -> None: ...
    def raise_exceptions(self) -> None: ...
    def clear_exceptions(self) -> None: ...
    def stop(self) -> None: ...

class ThreadPool:
    telebot: TeleBot
    tasks: Queue.Queue[tuple[Callable[..., Any], tuple[Any, ...], dict[str, Any]]]
    workers: list[WorkerThread]
    num_threads: int
    exception_event: threading.Event
    exception_info: _EXC_INFO | None
    def __init__(self, telebot: TeleBot, num_threads: int = 2) -> None: ...
    def put(self, func: Callable[..., Any], *args: Any, **kwargs: Any) -> None: ...
    def on_exception(self, worker_thread: WorkerThread, exc_info: _EXC_INFO) -> None: ...
    def raise_exceptions(self) -> None: ...
    def clear_exceptions(self) -> None: ...
    def close(self) -> None: ...

class AsyncTask:
    target: Callable[..., Any]
    args: Any
    kwargs: Any
    done: bool
    thread: threading.Thread
    def __init__(self, target: Callable[..., Any], *args: Any, **kwargs: Any) -> None: ...
    def wait(self) -> Any: ...

class CustomRequestResponse:
    status_code: int
    text: str
    reason: str
    def __init__(self, json_text: str, status_code: int = 200, reason: str = '') -> None: ...
    def json(self) -> Any: ...

def async_dec() -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def is_command(text: str) -> bool: ...
def extract_command(text: str) -> str | None: ...
def extract_arguments(text: str) -> str | None: ...
def split_string(text: str, chars_per_string: int) -> list[str]: ...
def smart_split(text: str, chars_per_string: int = ...) -> list[str]: ...
def escape(text: str) -> str | None: ...
def user_link(user: types.User, include_id: bool = False) -> str: ...
def quick_markup(values: dict[str, dict[str, Any]], row_width: int = 2) -> types.InlineKeyboardMarkup: ...
def or_set(self: threading.Event) -> None: ...
def or_clear(self: threading.Event) -> None: ...
def orify(e: Any, changed_callback: Callable[[], Any]) -> None: ...
def OrEvent(*events: threading.Event) -> threading.Event: ...
def per_thread(key: str, construct_value: Callable[..., Any], reset: bool = False) -> Any: ...
def deprecated(warn: bool = True, alternative: Callable[..., Any] | None = None, deprecation_text: str | None = None) -> Callable[[_T], _T]: ...
def webhook_google_functions(bot: TeleBot | AsyncTeleBot, request: Request) -> str | tuple[str, int]: ...
def antiflood(function: Callable[..., _TK], *args: Any, number_retries: int = 5, **kwargs: Any) -> Callable[..., _TK]: ...
def parse_web_app_data(token: str, raw_init_data: str) -> dict[str, Any]: ...
def validate_web_app_data(token: str, raw_init_data: str) -> bool: ...
def validate_token(token: str) -> bool: ...
def extract_bot_id(token: str) -> int | None: ...
