from _typeshed import Incomplete
from telebot.async_telebot import AsyncTeleBot as AsyncTeleBot
from telebot.states import State as State, resolve_context as resolve_context
from telebot.types import CallbackQuery as CallbackQuery, Message as Message

class StateContext:
    message: Message | CallbackQuery
    bot: AsyncTeleBot
    bot_id: Incomplete
    def __init__(self, message: Message | CallbackQuery, bot: AsyncTeleBot) -> None: ...
    async def set(self, state: State | str) -> bool: ...
    async def get(self) -> str: ...
    async def delete(self) -> bool: ...
    async def reset_data(self) -> bool: ...
    def data(self) -> dict: ...
    async def add_data(self, **kwargs) -> None: ...
