from _typeshed import Incomplete

class StateStorageBase:
    def __init__(self) -> None: ...
    async def set_data(self, chat_id, user_id, key, value, business_connection_id=None, message_thread_id=None, bot_id=None) -> None: ...
    async def get_data(self, chat_id, user_id) -> None: ...
    async def set_state(self, chat_id, user_id, state, business_connection_id=None, message_thread_id=None, bot_id=None) -> None: ...
    async def delete_state(self, chat_id, user_id, business_connection_id=None, message_thread_id=None, bot_id=None) -> None: ...
    async def reset_data(self, chat_id, user_id, business_connection_id=None, message_thread_id=None, bot_id=None) -> None: ...
    async def get_state(self, chat_id, user_id, business_connection_id=None, message_thread_id=None, bot_id=None) -> None: ...
    def get_interactive_data(self, chat_id, user_id, business_connection_id=None, message_thread_id=None, bot_id=None) -> None: ...
    async def save(self, chat_id, user_id, data) -> None: ...

class StateDataContext:
    obj: Incomplete
    data: Incomplete
    chat_id: Incomplete
    user_id: Incomplete
    bot_id: Incomplete
    business_connection_id: Incomplete
    message_thread_id: Incomplete
    def __init__(self, obj, chat_id, user_id, business_connection_id=None, message_thread_id=None, bot_id=None) -> None: ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc_val, exc_tb): ...
