from typing import Any
from types import TracebackType

class StateStorageBase:
    def __init__(self) -> None: ...
    async def set_data(self, chat_id: int | str, user_id: int, key: str, value: Any, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> Any: ...
    async def get_data(self, chat_id: int | str, user_id: int) -> dict[str, Any]: ...
    async def set_state(self, chat_id: int | str, user_id: int, state: str | Any | None, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> Any: ...
    async def delete_state(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> None: ...
    async def reset_data(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> Any: ...
    async def get_state(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> str | None: ...
    def get_interactive_data(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> StateDataContext: ...
    async def save(self, chat_id: int | str, user_id: int, data: dict[str, Any]) -> Any: ...


class StateDataContext:
    obj: StateStorageBase
    data: dict[str, Any]
    chat_id: int | str
    user_id: int
    bot_id: int | None
    business_connection_id: str | None
    message_thread_id: int | None

    def __init__(self, obj: StateStorageBase, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> None: ...
    async def __aenter__(self) -> dict[str, Any]: ...
    async def __aexit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None: ...
