from telebot.asyncio_storage.base_storage import StateDataContext as StateDataContext, StateStorageBase as StateStorageBase
from typing import Any

class StateMemoryStorage(StateStorageBase):
    separator: str | None
    prefix: str | None
    data: dict[str, Any]
    def __init__(self, separator: str | None = ':', prefix: str | None = 'telebot') -> None: ...
    async def set_state(self, chat_id: int | str, user_id: int, state: str | Any | None, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> Any: ...
    async def get_state(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> str | None: ...
    async def delete_state(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> None: ...
    async def set_data(self, chat_id: int | str, user_id: int, key: str, value: Any, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> Any: ...
    async def get_data(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> dict[str, Any]: ...
    async def reset_data(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> Any: ...
    def get_interactive_data(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> StateDataContext: ...
    async def save(self, chat_id: int | str, user_id: int, data: dict[str, Any], business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> Any: ...
