from _typeshed import Incomplete
from telebot.asyncio_storage.base_storage import StateDataContext as StateDataContext, StateStorageBase as StateStorageBase
from typing import Callable

aiofiles_installed: bool

def with_lock(func: Callable) -> Callable: ...

class StatePickleStorage(StateStorageBase):
    file_path: Incomplete
    prefix: Incomplete
    separator: Incomplete
    lock: Incomplete
    def __init__(self, file_path: str = './.state-save/states.pkl', prefix: str = 'telebot', separator: str | None = ':') -> None: ...
    def create_dir(self) -> None: ...
    @with_lock
    async def set_state(self, chat_id: int, user_id: int, state: str, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    @with_lock
    async def get_state(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> str | None: ...
    @with_lock
    async def delete_state(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    @with_lock
    async def set_data(self, chat_id: int, user_id: int, key: str, value: str | int | float | dict, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    @with_lock
    async def get_data(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> dict: ...
    @with_lock
    async def reset_data(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    def get_interactive_data(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> dict | None: ...
    @with_lock
    async def save(self, chat_id: int, user_id: int, data: dict, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
