from telebot.asyncio_storage.base_storage import StateDataContext as StateDataContext, StateStorageBase as StateStorageBase
from typing import Callable, Any, TypeVar
import threading

aiofiles_installed: bool

_F = TypeVar("_F", bound=Callable[..., Any])

def with_lock(func: _F) -> _F: ...

class StatePickleStorage(StateStorageBase):
    file_path: str
    prefix: str
    separator: str
    lock: threading.Lock
    def __init__(self, file_path: str = './.state-save/states.pkl', prefix: str = 'telebot', separator: str | None = ':') -> None: ...
    def create_dir(self) -> None: ...
    @with_lock
    async def set_state(self, chat_id: int | str, user_id: int, state: str | Any | None, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> Any: ...
    @with_lock
    async def get_state(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> str | None: ...
    @with_lock
    async def delete_state(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> None: ...
    @with_lock
    async def set_data(self, chat_id: int | str, user_id: int, key: str, value: Any, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> Any: ...
    @with_lock
    async def get_data(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> dict[str, Any]: ...
    @with_lock
    async def reset_data(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> Any: ...
    def get_interactive_data(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> StateDataContext: ...
    @with_lock
    async def save(self, chat_id: int | str, user_id: int, data: dict[str, Any], business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> Any: ...
