from _typeshed import Incomplete
from redis.asyncio import ConnectionPool as ConnectionPool
from telebot.asyncio_storage.base_storage import StateDataContext as StateDataContext, StateStorageBase as StateStorageBase
from typing import Callable, Coroutine

redis_installed: bool

def async_with_lock(func: Callable[..., Coroutine]) -> Callable[..., Coroutine]: ...
def async_with_pipeline(func: Callable[..., Coroutine]) -> Callable[..., Coroutine]: ...

class StateRedisStorage(StateStorageBase):
    separator: Incomplete
    prefix: Incomplete
    redis: Incomplete
    lock: Incomplete
    def __init__(self, host: str = 'localhost', port: int = 6379, db: int = 0, password=None, prefix: str = 'telebot', redis_url=None, connection_pool: ConnectionPool = None, separator: str | None = ':') -> None: ...
    @async_with_lock
    @async_with_pipeline
    async def set_state(self, pipe, chat_id: int, user_id: int, state: str, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    async def get_state(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> str | None: ...
    async def delete_state(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    @async_with_lock
    @async_with_pipeline
    async def set_data(self, pipe, chat_id: int, user_id: int, key: str, value: str | int | float | dict, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    async def get_data(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> dict: ...
    @async_with_lock
    @async_with_pipeline
    async def reset_data(self, pipe, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    def get_interactive_data(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> dict | None: ...
    @async_with_lock
    @async_with_pipeline
    async def save(self, pipe, chat_id: int, user_id: int, data: dict, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    def migrate_format(self, bot_id: int, prefix: str | None = 'telebot_'): ...
