from redis.asyncio import ConnectionPool as ConnectionPool
from telebot.asyncio_storage.base_storage import StateDataContext as StateDataContext, StateStorageBase as StateStorageBase
from typing import Any, Callable, Coroutine, TypeVar
from redis import Redis
from redis.asyncio.client import Pipeline

redis_installed: bool

_F = TypeVar("_F", bound=Callable[..., Coroutine[Any, Any, Any]])

def async_with_lock(func: _F) -> _F: ...
def async_with_pipeline(func: _F) -> _F: ...

class StateRedisStorage(StateStorageBase):
    separator: str | None
    prefix: str
    redis: Redis
    lock: Any # i have no idea
    def __init__(self, host: str = 'localhost', port: int = 6379, db: int = 0, password: str | None = None, prefix: str = 'telebot', redis_url: str | None = None, connection_pool: ConnectionPool | None = None, separator: str | None = ':') -> None: ...
    @async_with_lock
    @async_with_pipeline
    async def set_state(self, pipe: Pipeline, chat_id: int, user_id: int, state: str, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    async def get_state(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> str | None: ...
    async def delete_state(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    @async_with_lock
    @async_with_pipeline
    async def set_data(self, pipe: Pipeline, chat_id: int | str, user_id: int, key: str, value: str | int | float | dict[str, Any], business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    async def get_data(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> dict[str, Any]: ...
    @async_with_lock
    @async_with_pipeline
    async def reset_data(self, pipe: Pipeline, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    def get_interactive_data(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> dict[str, Any] | None: ...
    @async_with_lock
    @async_with_pipeline
    async def save(self, pipe: Pipeline, chat_id: int, user_id: int, data: dict[str, Any], business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    def migrate_format(self, bot_id: int, prefix: str | None = 'telebot_') -> None: ...
