from _typeshed import Incomplete
from telebot import TeleBot as TeleBot, types as types
from telebot.states import State as State, StatesGroup as StatesGroup, resolve_context as resolve_context
from telebot.types import CallbackQuery as CallbackQuery, Message as Message

class StateContext:
    message: Message | CallbackQuery
    bot: TeleBot
    bot_id: Incomplete
    def __init__(self, message: Message | CallbackQuery, bot: str) -> None: ...
    def set(self, state: State | str) -> bool: ...
    def get(self) -> str: ...
    def delete(self) -> bool: ...
    def reset_data(self) -> bool: ...
    def data(self) -> dict: ...
    def add_data(self, **kwargs) -> None: ...
