from types import TracebackType
from typing import Any

class StateStorageBase:
    def __init__(self) -> None: ...
    def set_data(self, chat_id: int | str, user_id: int, key: str, value: Any, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> None: ...
    def get_data(self, chat_id: int | str, user_id: int) -> Any: ...
    def set_state(self, chat_id: int | str, user_id: int, state: Any, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> Any: ...
    def delete_state(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> None: ...
    def reset_data(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> None: ...
    def get_state(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> Any: ...
    def get_interactive_data(self, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> Any: ...
    def save(self, chat_id: int | str, user_id: int, data: dict[str, Any]) -> Any: ...

class StateDataContext:
    obj: StateStorageBase
    data: dict[str, Any]
    chat_id: int | str
    user_id: int
    bot_id: int | None
    business_connection_id: str | None
    message_thread_id: int | None
    def __init__(self, obj: StateStorageBase, chat_id: int | str, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> None: ...
    def __enter__(self) -> dict[str, Any]: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None: ...
