from telebot.storage.base_storage import StateDataContext as StateDataContext, StateStorageBase as StateStorageBase
from typing import Callable, TypeVar, Any

_F = TypeVar("_F", bound=Callable[..., Any])

def with_lock(func: _F) -> _F: ...

class StatePickleStorage(StateStorageBase):
    file_path: str
    prefix: str
    separator: str | None
    lock: Any
    def __init__(self, file_path: str = './.state-save/states.pkl', prefix: str = 'telebot', separator: str | None = ':') -> None: ...
    def create_dir(self) -> None: ...
    @with_lock
    def set_state(self, chat_id: int, user_id: int, state: str, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    @with_lock
    def get_state(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> str | None: ...
    @with_lock
    def delete_state(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    @with_lock
    def set_data(self, chat_id: int, user_id: int, key: str, value: str | int | float | dict, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    @with_lock
    def get_data(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> dict[str, Any]: ...
    @with_lock
    def reset_data(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    def get_interactive_data(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> dict[str, Any] | None: ...
    @with_lock
    def save(self, chat_id: int, user_id: int, data: dict[str, Any], business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
