import redis
from _typeshed import Incomplete
from telebot.storage.base_storage import StateDataContext as StateDataContext, StateStorageBase as StateStorageBase

redis_installed: bool

class StateRedisStorage(StateStorageBase):
    separator: Incomplete
    prefix: Incomplete
    redis: Incomplete
    def __init__(self, host: str = 'localhost', port: int = 6379, db: int = 0, password=None, prefix: str = 'telebot', redis_url=None, connection_pool: redis.ConnectionPool = None, separator: str | None = ':') -> None: ...
    def set_state(self, chat_id: int, user_id: int, state: str, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    def get_state(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> str | None: ...
    def delete_state(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    def set_data(self, chat_id: int, user_id: int, key: str, value: str | int | float | dict, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    def get_data(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> dict: ...
    def reset_data(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    def get_interactive_data(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> dict | None: ...
    def save(self, chat_id: int, user_id: int, data: dict, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    def migrate_format(self, bot_id: int, prefix: str | None = 'telebot_'): ...
