import redis
from telebot.storage.base_storage import StateDataContext as StateDataContext, StateStorageBase as StateStorageBase

redis_installed: bool

class StateRedisStorage(StateStorageBase):
    separator: str | None
    prefix: str
    redis: redis.Redis
    def __init__(self, host: str = 'localhost', port: int = 6379, db: int = 0, password: str | None = None, prefix: str = 'telebot', redis_url: str | None = None, connection_pool: redis.ConnectionPool | None = None, separator: str | None = ':') -> None: ...
    def set_state(self, chat_id: int, user_id: int, state: str, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    def get_state(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> str | None: ...
    def delete_state(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    def set_data(self, chat_id: int, user_id: int, key: str, value: str | int | float | dict, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    def get_data(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> dict[str, Any]: ...
    def reset_data(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    def get_interactive_data(self, chat_id: int, user_id: int, business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> dict[str, Any] | None: ...
    def save(self, chat_id: int, user_id: int, data: dict[str, Any], business_connection_id: str | None = None, message_thread_id: int | None = None, bot_id: int | None = None) -> bool: ...
    def migrate_format(self, bot_id: int, prefix: str | None = 'telebot_'): ...
